services:
  postgres:
    image: postgres:15
    container_name: nestjs_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestjs_demo
    ports:
      - "5433:5432"
    volumes:
      - nestjs_postgresql_data:/var/lib/postgresql/data
    # Optional healthcheck. Currently it is a no-op.
    # It will be enabled only if the backend is dockerized too
    # and is marked as depends_on the postgres service.
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 5s
      retries: 5
      timeout: 3s

volumes:
  nestjs_postgresql_data:
