import { CreatePropertyDto } from '../src/properties/dto/create-property.dto';
import { PropertyStatus } from '../src/common/enums/property-status.enum';

// Sample properties
export const sampleProperties: CreatePropertyDto[] = [
  {
    city: 'Berlin',
    address: 'Alexanderplatz 1',
    totalPieces: 100,
    availablePieces: 100,
    soldPieces: 0,
    unitPrice: 5000,
    status: PropertyStatus.AVAILABLE,
  },
  {
    city: 'Munich',
    address: 'Marienplatz 8',
    totalPieces: 50,
    availablePieces: 50,
    soldPieces: 0,
    unitPrice: 8000,
    status: PropertyStatus.AVAILABLE,
  },
  {
    city: 'Hamburg',
    address: 'Jungfernstieg 3',
    totalPieces: 75,
    availablePieces: 25,
    soldPieces: 50,
    unitPrice: 6500,
    status: PropertyStatus.AVAILABLE,
  },
  {
    city: 'Cologne',
    address: 'Domstraße 10',
    totalPieces: 120,
    availablePieces: 0,
    soldPieces: 120,
    unitPrice: 7000,
    status: PropertyStatus.NOT_AVAILABLE,
  },
  {
    city: 'Frankfurt',
    address: 'Main Tower 20',
    totalPieces: 90,
    availablePieces: 90,
    soldPieces: 0,
    unitPrice: 9500,
    status: PropertyStatus.AVAILABLE,
  },
  {
    city: 'Stuttgart',
    address: 'Königstraße 25',
    totalPieces: 60,
    availablePieces: 60,
    soldPieces: 0,
    unitPrice: 7200,
    status: PropertyStatus.AVAILABLE,
  },
  {
    city: 'Leipzig',
    address: 'Augustusplatz 15',
    totalPieces: 80,
    availablePieces: 40,
    soldPieces: 40,
    unitPrice: 4800,
    status: PropertyStatus.AVAILABLE,
  },
  {
    city: 'Düsseldorf',
    address: 'Königsallee 99',
    totalPieces: 100,
    availablePieces: 100,
    soldPieces: 0,
    unitPrice: 6000,
    status: PropertyStatus.AVAILABLE,
  },
  {
    city: 'Bremen',
    address: 'Am Wall 12',
    totalPieces: 70,
    availablePieces: 10,
    soldPieces: 60,
    unitPrice: 5300,
    status: PropertyStatus.AVAILABLE,
  },
  {
    city: 'Nuremberg',
    address: 'Kaiserstraße 7',
    totalPieces: 40,
    availablePieces: 0,
    soldPieces: 40,
    unitPrice: 4300,
    status: PropertyStatus.HIDDEN,
  },
];
